In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [3]:
array.shape

(3,)

In [4]:
array2 = np.array([1,2,3,4,5,6,7,8,9])

array2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array2.ndim

1

In [6]:
array.dtype.name

'int32'

In [7]:
array2.size

9

In [8]:
type(array)

numpy.ndarray

In [9]:
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array3.shape

(3, 3)

In [11]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((2,2))

array([[2.12199579e-314, 7.63918485e-312],
       [6.58095440e-321, 7.63918485e-312]])

In [14]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
a = np.linspace(0,10,20)
a

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
a = np.array([3,5,6])
b = np.array([1,6,9])

print(a+b)

[ 4 11 15]


In [17]:
print(a-b)

[ 2 -1 -3]


In [18]:
print(a*b)

[ 3 30 54]


In [19]:
liste = [1,2,3,4]
array = np.array([12,14,16])

print(liste)
print(array)

[1, 2, 3, 4]
[12 14 16]


In [20]:
array = np.array(liste)
array

array([1, 2, 3, 4])

In [21]:
b = a
c = a
b[0] = 10

print(a,b,c)

[10  5  6] [10  5  6] [10  5  6]


In [22]:
d = a.copy()
d

array([10,  5,  6])

In [23]:
a[0] = 5

In [24]:
d

array([10,  5,  6])

In [25]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [26]:
print(a[0])

1


In [27]:
print(a[0:4])

[1 2 3 4]


In [28]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [29]:
b = np.array([[1,2,3,4,5],[8,9,10,11,12]])
b

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12]])

In [30]:
print(b[1,1])

9


In [31]:
print(b[:,3])

# : konulması hepsini yazdırmaya sebep olur.

[ 4 11]


In [32]:
print(b[1,:])

[ 8  9 10 11 12]


In [33]:
print(b[1,1:4])

[ 9 10 11]


In [34]:
b[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12]])

In [35]:
b[:,-1]

# -1 son satır ve son sutün yazdırır.

array([ 5, 12])

In [36]:
a = np.array([[1,2,3],[23,22,55],[45,12,16]])
a

array([[ 1,  2,  3],
       [23, 22, 55],
       [45, 12, 16]])

In [37]:
b = a.ravel()
b

# ravel: 2 boyutlu matrisi tek boyuta çevirdik.

array([ 1,  2,  3, 23, 22, 55, 45, 12, 16])

In [38]:
b.reshape(3,3)

array([[ 1,  2,  3],
       [23, 22, 55],
       [45, 12, 16]])

In [39]:
b

array([ 1,  2,  3, 23, 22, 55, 45, 12, 16])

In [40]:
b.resize(3,3)

In [41]:
b

array([[ 1,  2,  3],
       [23, 22, 55],
       [45, 12, 16]])